- name: apply roles
  hosts: dokku_servers
  roles:
  # add whatever roles you need
  - role: dokku_bot.ansible_dokku
    tags: dokku
    become: true
  tasks:
  - name: Create seekpath app
    dokku_clone:
      app: seekpath
      repository: https://github.com/materialscloud-org/tools-seekpath
      # version: v20.09.1
    tags: my_dokku_apps

  - name: Configure ports for seekpath app
    dokku_ports:
      app: seekpath
      mappings:
      - http:80:80
      - https:443:80
    tags: my_dokku_apps
